# Generated by Django 3.1.1 on 2020-12-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='categorySlug',
            new_name='slug',
        ),
    ]
