# Generated by Django 3.1.1 on 2020-11-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_fuckword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='yeet', max_length=20),
            preserve_default=False,
        ),
    ]
