# Generated by Django 3.1.1 on 2020-11-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
