# Generated by Django 3.1.1 on 2020-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201130_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('datePublished', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
